/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.Customer;
import jooqdata.tables.Lot;


/**
 * Convenience access to all tables in purchase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>purchase.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>purchase.lot</code>.
     */
    public static final Lot LOT = Lot.LOT;
}
