/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Purchase;
import jooqdata.tables.Customer.CustomerPath;
import jooqdata.tables.records.LotRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lot extends TableImpl<LotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>purchase.lot</code>
     */
    public static final Lot LOT = new Lot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LotRecord> getRecordType() {
        return LotRecord.class;
    }

    /**
     * The column <code>purchase.lot.id</code>.
     */
    public final TableField<LotRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>purchase.lot.lot_name</code>.
     */
    public final TableField<LotRecord, String> LOT_NAME = createField(DSL.name("lot_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>purchase.lot.customer_code</code>.
     */
    public final TableField<LotRecord, String> CUSTOMER_CODE = createField(DSL.name("customer_code"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.lot.price</code>.
     */
    public final TableField<LotRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>purchase.lot.currency_code</code>.
     */
    public final TableField<LotRecord, String> CURRENCY_CODE = createField(DSL.name("currency_code"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>purchase.lot.nds_rate</code>.
     */
    public final TableField<LotRecord, String> NDS_RATE = createField(DSL.name("nds_rate"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>purchase.lot.place_delivery</code>.
     */
    public final TableField<LotRecord, String> PLACE_DELIVERY = createField(DSL.name("place_delivery"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.lot.date_delivery</code>.
     */
    public final TableField<LotRecord, LocalDateTime> DATE_DELIVERY = createField(DSL.name("date_delivery"), SQLDataType.LOCALDATETIME(6), this, "");

    private Lot(Name alias, Table<LotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lot(Name alias, Table<LotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>purchase.lot</code> table reference
     */
    public Lot(String alias) {
        this(DSL.name(alias), LOT);
    }

    /**
     * Create an aliased <code>purchase.lot</code> table reference
     */
    public Lot(Name alias) {
        this(alias, LOT);
    }

    /**
     * Create a <code>purchase.lot</code> table reference
     */
    public Lot() {
        this(DSL.name("lot"), null);
    }

    public <O extends Record> Lot(Table<O> path, ForeignKey<O, LotRecord> childPath, InverseForeignKey<O, LotRecord> parentPath) {
        super(path, childPath, parentPath, LOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LotPath extends Lot implements Path<LotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LotPath(Table<O> path, ForeignKey<O, LotRecord> childPath, InverseForeignKey<O, LotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LotPath(Name alias, Table<LotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LotPath as(String alias) {
            return new LotPath(DSL.name(alias), this);
        }

        @Override
        public LotPath as(Name alias) {
            return new LotPath(alias, this);
        }

        @Override
        public LotPath as(Table<?> alias) {
            return new LotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Purchase.PURCHASE;
    }

    @Override
    public Identity<LotRecord, Long> getIdentity() {
        return (Identity<LotRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LotRecord> getPrimaryKey() {
        return Keys.LOT_PK;
    }

    @Override
    public List<ForeignKey<LotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LOT__LOT_CUSTOMER_FK);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>purchase.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.LOT__LOT_CUSTOMER_FK, null);

        return _customer;
    }

    @Override
    public List<Check<LotRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_currency_list"), "(((currency_code)::text = ANY ((ARRAY['RUB'::character varying, 'USD'::character varying, 'EUR'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("chk_nds_rate"), "(((nds_rate)::text = ANY ((ARRAY['Без НДС'::character varying, '18%'::character varying, '20%'::character varying])::text[])))", true)
        );
    }

    @Override
    public Lot as(String alias) {
        return new Lot(DSL.name(alias), this);
    }

    @Override
    public Lot as(Name alias) {
        return new Lot(alias, this);
    }

    @Override
    public Lot as(Table<?> alias) {
        return new Lot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(String name) {
        return new Lot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Name name) {
        return new Lot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Table<?> name) {
        return new Lot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Condition condition) {
        return new Lot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, BigDecimal, String, String, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super String, ? super String, ? super BigDecimal, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super String, ? super String, ? super BigDecimal, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
